name: gas_out_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  url_launcher:
  mobx:
  flutter_mobx: ^2.0.4
  get_it:
  cloud_firestore: ^3.1.10
  http: ^0.13.4
  mysql1:
  intl: ^0.17.0
  brasil_fields: ^1.3.1
  firebase_core: ^1.13.1
  firebase_analytics: ^9.1.2
  firebase_messaging: ^11.2.10
  flutter_local_notifications: ^9.4.0
  firebase_auth: ^3.3.10
  flutter_native_splash: ^2.1.1
  bordered_text:
  kf_drawer: ^1.1.1
  google_fonts: ^2.3.2
  dio: ^4.0.6
  flutter_modular: ^4.5.1+1
  flutter_launcher_icons: ^0.9.2
  shared_preferences: ^2.0.13
  font_awesome_flutter:
  simple_animations:
  email_validator: ^2.0.1
  flutter_svg: ^1.0.3
  mqtt_client: ^9.6.7
  ndialog: ^4.1.1

flutter_native_splash:
  image: "assets/images/logo.png"
  color: "#ffffff"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/images/iconeVermelhoFundoBranco.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/iconeVermelho.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mobx_codegen:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/images/creative.png
    - assets/images/sala.jpg
    - assets/images/banheiro.jpg
    - assets/images/quarto.jpg
    - assets/images/garagem.jpg
    - assets/images/cozinha.jpg
    - assets/images/logoPequena.png
    - assets/images/logoPequenaBranco.png
    - assets/images/sprinkler.png
    - assets/images/notification.png
    - assets/images/icWhatsApp.png
    - assets/images/icTelegram.png
    - assets/images/iconeVermelhoFundoBranco.png
    - assets/images/iconeVermelho.png
    - assets/images/icon-banheiro.png
    - assets/images/icon-quarto.png
    - assets/images/icon-garagem.png
    - assets/images/icon-cozinha.png
    - assets/images/icon-lavanderia.png
    - assets/images/icon-sala.png
    - assets/images/otp.svg
    - assets/certs/RootCA.pem
    - assets/certs/DeviceCertificate.crt
    - assets/certs/Private.key
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #  fonts:
  #    - family: Pacifico
  #      fonts:
  #        - asset: fonts/Pacifico-Regular.ttf
  #    - family: Roboto
  #      fonts:
  #        - asset: fonts/Roboto-Regular.ttf
  #    - family: OpenSansRegular
  #      fonts:
  #        - asset: fonts/OpenSans-Regular.ttf
  #    - family: OpenSansLight
  #      fonts:
  #        - asset: fonts/OpenSans-Light.ttf
  #    - family: OpenSansBold
  #      fonts:
  #        - asset: fonts/OpenSans-Bold.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
